// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsqczcxofhunxgvvmobg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzcWN6Y3hvZmh1bnhndnZtb2JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjAzNzYsImV4cCI6MjA2ODY5NjM3Nn0.ZMQQUq4bc5OR_eZiQ36PY_PLoGlzA17BcYZFVPrdCZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});